spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.15.128:3308/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    schema:
#      - classpath:t_employee.sql